#!/bin/bash

ALARM="$HOME/Music/tones/alarm.oga"

#before
VOL=$(pamixer --get-volume)
sleep $1
pamixer --allow-boost --set-volume 100


#main
mpv "$ALARM"

#after
pamixer --allow-boost --set-volume $VOL
