#!/bin/bash
if [[ $1 == "--rofi" ]];then
	url=$(buku --nostdin -p -f4 | rofi -dmenu | cut -f2 )
else
	url=$(buku -p -f4 | fzf -m --reverse --preview "buku --nostdin -p {1}" --preview-window=wrap | cut -f2)
fi

if [ -n "$url" ]; then
	echo "$url" | xargs firefox
fi
