#!/usr/bin/env python3
# Creates a virtual xbox controller for ipega controller

import re
import os

# get the text from devices file
file = open("/proc/bus/input/devices")
text = file.read()
file.close()

# split devices file into a dict
dev = text.split("\n\n")

# make each device into a dict itself
for x in range(len(dev)):
    dev[x] = dev[x].split("\n")

# function that returns the entry for the Ipega controller (returns None if not found)
def find_joy():
    devlen = len(dev) - 1
    joy = None
    for x in range(devlen):
        name = dev[x][1]
        if name == 'N: Name="ipega media gamepad controller"':
            joy = dev[x]    
    return joy
    
# set joy to the ipega controller
joy = find_joy()

# function to return event number
def eventN ():
    event = re.search("event..", joy[5]).group()
    event = re.sub("event", "", event)
    return event
# this is the command for emulating the xbox controller

command = "sudo xboxdrv --evdev /dev/input/event{} --evdev-absmap ABS_X=x1,ABS_Y=y1,ABS_Z=x2,ABS_RZ=y2,ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y --axismap -Y1=Y1,-Y2=Y2 --evdev-keymap BTN_A=a,BTN_B=b,BTN_X=x,BTN_Y=y,BTN_TL=lb,BTN_TR=rb,BTN_TL2=lt,BTN_TR2=rt,BTN_THUMBL=tl,BTN_THUMBR=tr,BTN_SELECT=back,BTN_START=start --silent &"

if joy != None:
    command = re.sub("{}", eventN(), command)
    os.system(command)
else:
    print("joy not found")

