#!/bin/bash
# Radio list location
radio_list="$HOME/.config/radio.list"

# If radio list not exist create it
[ -f "$radio_list" ] || touch "$radio_list"

station_name=$(sed 's/||.*$//' $radio_list|fzf -1 -q "$*" --border)
station_url=$(grep "^$station_name||" "$radio_list"|sed 's/^.*||//')
if ! [ -z "$station_name" ]; then
	clear
	echo "Playing: $station_name"
	mpv "$station_url" --no-video
fi
