#!/bin/sh
# Based on
# Original in https://github.com/dylanaraps/pfetch
# Take a screenshot.

scr_dir=~/Pictures/screenshots
xdpyinfo | awk '/dimensions/{print $2}'>/tmp/scr

date=$(date +%F)
time=$(date +%H-%M-%S)
vid_size=$(cat /tmp/scr)
echo $vid_size
file=$scr_dir/$date/$date-$time.jpg

mkdir -p "$scr_dir/$date"

ffmpeg -y \
    -f x11grab \
    -video_size $vid_size \
    -i :0.0 \
    -vframes 1 \
    "$file" 2>/dev/null

# ffmpeg -y \
#     -f x11grab \
#     -video_size $vid_size \
#     -i :0.0 \
#     -vframes 1 \
#     "${file%%.jpg}.png" 2>/dev/null

cp -f "$file" "$scr_dir/current.jpg"
# cp -f "${file%%.jpg}.png" "$scr_dir/current.png"
