#!/bin/bash
stylus_id=$(xinput list|grep stylus|cut -f2|tr -d "id=")

case $1 in
	#TODO: Create a toggle between relative and absolute
	abs)
		xsetwacom set "$stylus_id" Mode Absolute
	;;

	rel)
		xsetwacom set "$stylus_id" Mode Relative
	;;

	small)
		xsetwacom set "$stylus_id" Area 5000 5700 10200 8550
	;;

	*)
		xsetwacom set "Wacom One by Wacom S Pen stylus" Area 0 0 15200 8550
	;;
esac

