#!/bin/bash

if [ "$1" == "--init" ]; then
    # here is the inicialization and installing applications
    pacman-key --init && pacman-key --populate

    pacman -Syu clang 



else
    # Here start the initial step for installing the pacman bootstrap
    # Download wget for downloading resources
    pkg install wget
    #Go to the folder for termux files
    pushd "$PREFIX/.."
        #Download pacman bootstrap from github releases
        wget `curl -s https://api.github.com/repos/termux/termux-packages/releases/latest | grep 'bootstrap-aarch64\.zip'  | tail -1 | cut -d : -f 2,3  | tr -d \"`
        unzip bootstrap-aarch64.zip -d usr-n

        pushd usr-n
            cat SYMLINKS.txt | awk -F "←" '{system("ln -s '"'"'"$1"'"'"' '"'"'"$2"'"'"'")}'
        popd
        popd

        echo "BOOTSTRAP: Next, must reboot termux in failsafe mode."
        echo "Must also manually remove usr folder and rename usr-n."
        echo "After, you can run this script with the --init flag"
    fi
popd
