#!/bin/bash

if [ "$1" == "--init" ]; then
    # here is the inicialization and installing applications
    pacman-key --init && pacman-key --populate
    TERMINAL_BASICS="git stow neovim wget iproute2 openssh ncurses-utils which fasd fzf make htop rsync xclip"
    LANGUAGES="clang python pypy rust golang lua53 nodejs"
    PROGRAMS="lazygit aria2 gh vifm mpv cmus ffplay imagemagick nmap-ncat"
    TERMUX="termux-x11 termux-api"
    X11="xorg-server-xephyr xorg-xsetroot xorgproto openbox tigervnc picom firefox keepassxc nitrogen pavucontrol thunar xfce4-clipman-plugin sxhkd picom"
    pacman -Syu base-devel $TERMINAL_BASICS $PROGRAMS $LANGUAGES $X11

    # Downloading my stuff and configurations

    if [ ! -e "$HOME/git" ]; then
        GITHUB="https://github.com"
        USER="fryedbiscuit"
        mkdir ~/git
        pushd ~/git
                #Let's start with mt dotfiles
                if [ ! -e dotfiles ]; then
                    git clone $GITHUB/$USER/dotfiles
                    pushd dotfiles
                        stow --dotfiles stow termux
                    popd
                fi

                #Now dwm
                if [ ! -e dwm ]; then
                    git clone $GITHUB/$USER/dwm
                    # if dwm isn't installed
                    if [ ! $(command -v dwm) ]; then
                        pushd dwm
                            git checkout termux
                            
                            make install
                            make clean
                        popd
                    fi
                fi

                # Now st

                if [ ! -e st ]; then
                git clone $GITHUB/$USER/st
                    # if st isn't installed
                    if [ ! $(command -v st) ]; then
                        pushd st
                            git checkout termux
                            
                            make install
                            make clean
                        popd
                    fi
                fi
            popd
    fi

else

    # Here start the initial step for installing the pacman bootstrap
    # Download wget for downloading resources
    yes|pkg install wget
    #Go to the folder for termux files
    pushd "$PREFIX/.."
        #Download pacman bootstrap from github releases
        wget `curl -s https://api.github.com/repos/termux-pacman/termux-packages/releases/latest | grep 'bootstrap-aarch64\.zip'  | tail -1 | cut -d : -f 2,3  | tr -d \"`

        unzip bootstrap-aarch64.zip -d usr-n

        pushd usr-n
            cat SYMLINKS.txt | awk -F "←" '{system("ln -s '"'"'"$1"'"'"' '"'"'"$2"'"'"'")}'
        popd

        echo "BOOTSTRAP: Next, must reboot termux in failsafe mode."
        echo "Must also manually remove usr folder and rename usr-n."
        echo "After, you can run this script with the --init flag"
    popd
fi
