#!/bin/bash

terminal="st -n float"
temp=$(mktemp)

if read -t 0 ; then
	cat - > $temp
	# cat <&0 > $temp
	$terminal -e bash -c "cat $temp | fzf "$@" |tee $temp"
else 
	echo no
	$terminal -e bash -c "fzf "$@" > $temp"
fi

cat $temp

